
ALTER TABLE reg_users
ADD COLUMN verify INT DEFAULT NULL,
ADD COLUMN created_at DATETIME NOT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL,
ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
 
 SELECT * FROM   reg_users
 